-- Parallel SQL schema for SuperScreens (KV remains active)
-- Apply in Supabase SQL editor or via migrations.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id text,
  email text,
  role text not null default 'client' check (role in ('admin', 'client', 'advertiser')),
  nome_fantasia text,
  razao_social text,
  logo_url text,
  logo_path text,
  rss_url text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_configs (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  news_rss_url text,
  logo_url text,
  active_template text default 'fullscreen',
  cycle_ratio integer default 70,
  updated_at timestamptz default now()
);

create table if not exists public.global_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.media_items (
  id uuid default gen_random_uuid() primary key,
  legacy_id text,
  owner_id uuid references public.profiles(id) on delete cascade,
  title text,
  url text,
  path text,
  type text check (type in ('video', 'image', 'youtube')),
  duration integer default 15,
  layout text default 'all',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.playlists (
  id uuid default gen_random_uuid() primary key,
  legacy_id text,
  owner_id uuid references public.profiles(id) on delete cascade,
  name text,
  items jsonb default '[]'::jsonb,
  settings jsonb default '{"shuffle": false}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ads (
  id uuid default gen_random_uuid() primary key,
  advertiser_id uuid references public.profiles(id) on delete cascade,
  media_item_id uuid references public.media_items(id) on delete set null,
  layout text default 'fullscreen',
  active boolean default true,
  impressions_count bigint default 0,
  created_at timestamptz default now()
);

create table if not exists public.client_advertisers (
  client_id uuid references public.profiles(id) on delete cascade,
  advertiser_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (client_id, advertiser_id)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  advertiser_id uuid references public.profiles(id),
  type text check (type in ('ad', 'media', 'tv', 'jukebox')),
  message text not null,
  created_at timestamptz default now()
);

create table if not exists public.player_status (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  last_seen timestamptz not null,
  current_media text,
  is_online boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.ad_impressions (
  id bigint generated by default as identity primary key,
  advertiser_id uuid references public.profiles(id),
  ad_id uuid references public.ads(id),
  ad_ref text,
  layout text,
  created_at timestamptz default now()
);

create table if not exists public.jukebox_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  title text not null,
  created_at timestamptz default now()
);

create table if not exists public.jukebox_stats_daily (
  day date primary key,
  count integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.system_stats (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_user_configs_updated_at
before update on public.user_configs
for each row execute function public.set_updated_at();

create trigger set_global_config_updated_at
before update on public.global_config
for each row execute function public.set_updated_at();

create trigger set_playlists_updated_at
before update on public.playlists
for each row execute function public.set_updated_at();

create trigger set_player_status_updated_at
before update on public.player_status
for each row execute function public.set_updated_at();

create trigger set_jukebox_stats_daily_updated_at
before update on public.jukebox_stats_daily
for each row execute function public.set_updated_at();

create trigger set_system_stats_updated_at
before update on public.system_stats
for each row execute function public.set_updated_at();

create index if not exists idx_profiles_legacy_id on public.profiles (legacy_id);
create index if not exists idx_media_items_owner_id on public.media_items (owner_id);
create index if not exists idx_media_items_legacy_id on public.media_items (legacy_id);
create index if not exists idx_playlists_owner_id on public.playlists (owner_id);
create index if not exists idx_playlists_legacy_id on public.playlists (legacy_id);
create index if not exists idx_ads_advertiser_id on public.ads (advertiser_id);
create index if not exists idx_client_advertisers_advertiser_id on public.client_advertisers (advertiser_id);
create index if not exists idx_activity_logs_created_at on public.activity_logs (created_at desc);
create index if not exists idx_player_status_last_seen on public.player_status (last_seen desc);
create index if not exists idx_ad_impressions_created_at on public.ad_impressions (created_at desc);
create index if not exists idx_jukebox_requests_created_at on public.jukebox_requests (created_at desc);
