-- Parallel SQL schema for SuperScreens (KV remains active)
-- Apply in Supabase SQL editor or via migrations.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'client' check (role in ('admin', 'client', 'advertiser')),
  nome_fantasia text,
  razao_social text,
  logo_url text,
  logo_path text,
  rss_url text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_configs (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  news_rss_url text,
  logo_url text,
  active_template text default 'fullscreen',
  cycle_ratio integer default 70,
  updated_at timestamptz default now()
);

create table if not exists public.global_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.media_items (
  id uuid default gen_random_uuid() primary key,
  legacy_id text,
  owner_id uuid references public.profiles(id) on delete cascade,
  title text,
  url text,
  path text,
  type text check (type in ('video', 'image', 'youtube')),
  duration integer default 15,
  layout text default 'all',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.playlists (
  id uuid default gen_random_uuid() primary key,
  legacy_id text,
  owner_id uuid references public.profiles(id) on delete cascade,
  name text,
  items jsonb default '[]'::jsonb,
  settings jsonb default '{"shuffle": false}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ads (
  id uuid default gen_random_uuid() primary key,
  advertiser_id uuid references public.profiles(id) on delete cascade,
  media_item_id uuid references public.media_items(id) on delete set null,
  layout text default 'fullscreen',
  active boolean default true,
  impressions_count bigint default 0,
  created_at timestamptz default now()
);

create table if not exists public.client_advertisers (
  client_id uuid references public.profiles(id) on delete cascade,
  advertiser_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (client_id, advertiser_id)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  advertiser_id uuid references public.profiles(id),
  type text check (type in ('ad', 'media', 'tv', 'jukebox')),
  message text not null,
  created_at timestamptz default now()
);

create table if not exists public.player_status (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  last_seen timestamptz not null,
  current_media text,
  is_online boolean default true,
  updated_at timestamptz default now()
);

create table if not exists public.ad_impressions (
  id bigint generated by default as identity primary key,
  advertiser_id uuid references public.profiles(id),
  ad_id uuid references public.ads(id),
  ad_ref text,
  layout text,
  created_at timestamptz default now()
);

create table if not exists public.jukebox_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  title text not null,
  created_at timestamptz default now()
);

create table if not exists public.jukebox_stats_daily (
  day date primary key,
  count integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.system_stats (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_user_configs_updated_at
before update on public.user_configs
for each row execute function public.set_updated_at();

create trigger set_global_config_updated_at
before update on public.global_config
for each row execute function public.set_updated_at();

create trigger set_playlists_updated_at
before update on public.playlists
for each row execute function public.set_updated_at();

create trigger set_player_status_updated_at
before update on public.player_status
for each row execute function public.set_updated_at();

create trigger set_jukebox_stats_daily_updated_at
before update on public.jukebox_stats_daily
for each row execute function public.set_updated_at();

create trigger set_system_stats_updated_at
before update on public.system_stats
for each row execute function public.set_updated_at();

create index if not exists idx_media_items_owner_id on public.media_items (owner_id);
create index if not exists idx_media_items_legacy_id on public.media_items (legacy_id);
create index if not exists idx_playlists_owner_id on public.playlists (owner_id);
create index if not exists idx_playlists_legacy_id on public.playlists (legacy_id);
create index if not exists idx_ads_advertiser_id on public.ads (advertiser_id);
create index if not exists idx_client_advertisers_advertiser_id on public.client_advertisers (advertiser_id);
create index if not exists idx_activity_logs_created_at on public.activity_logs (created_at desc);
create index if not exists idx_player_status_last_seen on public.player_status (last_seen desc);
create index if not exists idx_ad_impressions_created_at on public.ad_impressions (created_at desc);
create index if not exists idx_jukebox_requests_created_at on public.jukebox_requests (created_at desc);
-- RLS policies for the parallel SQL schema

create or replace function public.current_role()
returns text
language sql
stable
as $$
  select coalesce(auth.jwt()->'user_metadata'->>'role', 'user');
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select public.current_role() = 'admin';
$$;

alter table public.profiles enable row level security;
alter table public.user_configs enable row level security;
alter table public.global_config enable row level security;
alter table public.media_items enable row level security;
alter table public.playlists enable row level security;
alter table public.ads enable row level security;
alter table public.client_advertisers enable row level security;
alter table public.activity_logs enable row level security;
alter table public.player_status enable row level security;
alter table public.ad_impressions enable row level security;
alter table public.jukebox_requests enable row level security;
alter table public.jukebox_stats_daily enable row level security;
alter table public.system_stats enable row level security;

-- profiles
create policy profiles_select_self on public.profiles
  for select using (auth.uid() = id);

create policy profiles_insert_self on public.profiles
  for insert with check (auth.uid() = id);

create policy profiles_update_self on public.profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);

create policy profiles_admin_all on public.profiles
  for all using (public.is_admin())
  with check (public.is_admin());

-- user_configs
create policy user_configs_select_self on public.user_configs
  for select using (auth.uid() = user_id or public.is_admin());

create policy user_configs_write_self on public.user_configs
  for insert with check (auth.uid() = user_id or public.is_admin());

create policy user_configs_update_self on public.user_configs
  for update using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

-- global_config (admin only)
create policy global_config_admin_select on public.global_config
  for select using (public.is_admin());

create policy global_config_admin_write on public.global_config
  for insert with check (public.is_admin());

create policy global_config_admin_update on public.global_config
  for update using (public.is_admin())
  with check (public.is_admin());

create policy global_config_admin_delete on public.global_config
  for delete using (public.is_admin());

-- media_items
create policy media_items_select_owner on public.media_items
  for select using (auth.uid() = owner_id or public.is_admin());

create policy media_items_insert_owner on public.media_items
  for insert with check (auth.uid() = owner_id or public.is_admin());

create policy media_items_update_owner on public.media_items
  for update using (auth.uid() = owner_id or public.is_admin())
  with check (auth.uid() = owner_id or public.is_admin());

create policy media_items_delete_owner on public.media_items
  for delete using (auth.uid() = owner_id or public.is_admin());

-- playlists
create policy playlists_select_owner on public.playlists
  for select using (auth.uid() = owner_id or public.is_admin());

create policy playlists_insert_owner on public.playlists
  for insert with check (auth.uid() = owner_id or public.is_admin());

create policy playlists_update_owner on public.playlists
  for update using (auth.uid() = owner_id or public.is_admin())
  with check (auth.uid() = owner_id or public.is_admin());

create policy playlists_delete_owner on public.playlists
  for delete using (auth.uid() = owner_id or public.is_admin());

-- ads
create policy ads_select_owner on public.ads
  for select using (auth.uid() = advertiser_id or public.is_admin());

create policy ads_insert_owner on public.ads
  for insert with check (auth.uid() = advertiser_id or public.is_admin());

create policy ads_update_owner on public.ads
  for update using (auth.uid() = advertiser_id or public.is_admin())
  with check (auth.uid() = advertiser_id or public.is_admin());

create policy ads_delete_owner on public.ads
  for delete using (auth.uid() = advertiser_id or public.is_admin());

-- client_advertisers
create policy client_advertisers_select_parties on public.client_advertisers
  for select using (
    auth.uid() = client_id
    or auth.uid() = advertiser_id
    or public.is_admin()
  );

create policy client_advertisers_admin_write on public.client_advertisers
  for insert with check (public.is_admin());

create policy client_advertisers_admin_update on public.client_advertisers
  for update using (public.is_admin())
  with check (public.is_admin());

create policy client_advertisers_admin_delete on public.client_advertisers
  for delete using (public.is_admin());

-- activity_logs (admin only)
create policy activity_logs_admin_select on public.activity_logs
  for select using (public.is_admin());

create policy activity_logs_admin_insert on public.activity_logs
  for insert with check (public.is_admin());

-- player_status
create policy player_status_admin_select on public.player_status
  for select using (public.is_admin() or auth.uid() = user_id);

create policy player_status_write_self on public.player_status
  for insert with check (auth.uid() = user_id or public.is_admin());

create policy player_status_update_self on public.player_status
  for update using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

-- ad_impressions (admin only)
create policy ad_impressions_admin_select on public.ad_impressions
  for select using (public.is_admin());

create policy ad_impressions_admin_insert on public.ad_impressions
  for insert with check (public.is_admin());

-- jukebox_requests
create policy jukebox_requests_admin_select on public.jukebox_requests
  for select using (public.is_admin());

create policy jukebox_requests_insert_auth on public.jukebox_requests
  for insert with check (auth.uid() is not null or public.is_admin());

-- jukebox_stats_daily (admin only)
create policy jukebox_stats_daily_admin_select on public.jukebox_stats_daily
  for select using (public.is_admin());

create policy jukebox_stats_daily_admin_write on public.jukebox_stats_daily
  for insert with check (public.is_admin());

create policy jukebox_stats_daily_admin_update on public.jukebox_stats_daily
  for update using (public.is_admin())
  with check (public.is_admin());

-- system_stats (admin only)
create policy system_stats_admin_select on public.system_stats
  for select using (public.is_admin());

create policy system_stats_admin_write on public.system_stats
  for insert with check (public.is_admin());

create policy system_stats_admin_update on public.system_stats
  for update using (public.is_admin())
  with check (public.is_admin());
